In [1]:
# 11. HAFTA => VERİ BİLİMİNE GİRİŞ

In [5]:
import numpy as np

In [7]:
# İlk olarak, bir listeyi numpy array'e dönüştürüp aradaki farkı görelim
my_list_1 = [1,2,56,78]
print(type(my_list_1))

# Bir listeyi array'e dönüştürmenin en kısa ve bilindik yolu
my_array_1 = np.array(my_list_1)
print(type(my_array_1))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
my_array_2 = np.arange(11)
print(my_array_2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
# 5'ten başlayarak 56'ya kadar (56 dahil değil)
# 5'er 5'er artan sayılardan oluşan bir array tanımlayın

my_array_3 = np.arange(5,56,5)
print(my_array_3)

[ 5 10 15 20 25 30 35 40 45 50 55]


In [27]:
my_array_4 = np.array([5,46,0,-101,"12",True,45.965],dtype=np.int32)
print(my_array_4)
print(my_array_4.dtype)

[   5   46    0 -101   12    1   45]
int32


In [ ]:
import math
import random

In [29]:
# Rastgele int sayı üretimi
# 1 adet sayı 
print(np.random.randint(5,55))

15


In [31]:
# Eğer tek bir değer değil de bir matris üretmek istiyosanız

print(np.random.randint(1,101,(3,3)))

[[23 72 25]
 [81  5 17]
 [91 98 71]]


In [35]:
matris_1 = np.random.randint(1,101,(4,2))
print(matris_1)
print("-"*50)
# bir matristeki temel özellikler
print(f"Matrisin boyutu = {matris_1.shape}")
print(f"Matrisin satır sayısı = {matris_1.shape[0]}")
print(f"Matrisin sütun sayısı = {matris_1.shape[1]}")
print(f"Matrisin eleman sayısı = {matris_1.size}")
print(f"Matrisin boyutu = {matris_1.ndim}")

[[92 44]
 [21 70]
 [ 1 78]
 [59 23]]
--------------------------------------------------
Matrisin boyutu = (4, 2)
Matrisin satır sayısı = 4
Matrisin sütun sayısı = 2
Matrisin eleman sayısı = 8
Matrisin boyutu = 2


In [39]:
# 1 ile 10 arasında 2x2 boyutunda 2 matris tanımlayın
# Yapılacaklar
# 1) iki matris ile 4 temel matematiksel işlemi yapın
# Yani iki matrisi birbiriyle toplayın, çarpın, çıkarın, bölün
# 2) iki matrisin de 7 ile bölümünden kalanlarını verin
# Yani 2 matriste de yer alan sayıların 7 ile bölümünden kalanını yazdırın
# 3) İki matristeki tüm sayıların karesini hesaplayıp yazdırın
# NOT: tüm bu işlemleri yaparken her iki matrisi de bir integer değişken gibi
# düşünün


In [41]:
# 1 ile 10 arasında 2x2 boyutunda 2 matris tanımlayın
new_matris_1 = np.random.randint(1,11,(2,2))
new_matris_2 = np.random.randint(1,11,(2,2))

print(f"Matris_1 = {new_matris_1}")
print(f"Matris_2 = {new_matris_2}")

Matris_1 = [[4 9]
 [2 5]]
Matris_2 = [[5 8]
 [7 3]]


In [45]:
# Yapılacaklar
# 1) iki matris ile 4 temel matematiksel işlemi yapın
# Yani iki matrisi birbiriyle toplayın, çarpın, çıkarın, bölün

print(f"Toplam = {new_matris_1+new_matris_2}")
print("-"*50)
print(f"Çıkarma = {new_matris_1-new_matris_2}")
print("-"*50)
print(f"Bölme = {new_matris_1/new_matris_2}")
print("-"*50)
print(f"Çarpma = {new_matris_1*new_matris_2}")
print("-"*50)

Toplam = [[ 9 17]
 [ 9  8]]
--------------------------------------------------
Çıkarma = [[-1  1]
 [-5  2]]
--------------------------------------------------
Bölme = [[0.8        1.125     ]
 [0.28571429 1.66666667]]
--------------------------------------------------
Çarpma = [[20 72]
 [14 15]]
--------------------------------------------------


In [49]:
# NOT: Lineer Cebirde iki matrisin çarpımının özel bir şartı vardır
# Buna göre, ilk matrisin sütun sayısı ile ikinci matrisin
# satır sayısının birbirine eşit olması lazım.

# Python'da şartları taşıyan iki matrisin çarpım işlemi aşağıdaki gibi
# yapılır.

# 1. Yol: (numpy ile)
print(np.dot(new_matris_1,new_matris_2))

print("-"*50)

#@ karakteri ile (@ karakteri * işleminin yerini alır)
print(new_matris_1@new_matris_1)

[[83 59]
 [45 31]]
--------------------------------------------------
[[34 81]
 [18 43]]


In [51]:
# Özel matris üretme

# Sadece sıfırlardan oluşan ve istenilen boyutlarda (5x3) matris üretme
my_array_5_zeros = np.zeros((5,3))

# Sadece birlerden oluşan ve istenilen boyutlarda (4x3) matris üretme
my_array_6_ones = np.ones((5,3))

# Diyagonal matris
my_array_7_diagonal = np.eye(6)

# İstenilen boyutlarda tamamen aynı değerden oluşan matris
# Örneğin 3x3 boyutunda tamamen 8 sayısından oluşan matris
my_array_8_full = np.full((3,3),8)

print(f"Sadece sıfırlardan oluşan matris = {my_array_5_zeros}")
print("-"*50)
print(f"Sadece birlerden oluşan matris = {my_array_6_ones}")
print("-"*50)
print(f"Diyagonal matris = {my_array_7_diagonal}")
print("-"*50)
print(f"Tamamen aynı değerlerden oluşan matris = {my_array_8_full}")
print("-"*50)

Sadece sıfırlardan oluşan matris = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
Sadece birlerden oluşan matris = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
Diyagonal matris = [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
--------------------------------------------------
Tamamen aynı değerlerden oluşan matris = [[8 8 8]
 [8 8 8]
 [8 8 8]]
--------------------------------------------------


In [53]:
my_array_9 = np.random.randint(1,101,(4,3))

print(my_array_9)

[[69 73 89]
 [18  1 83]
 [83 69 38]
 [57 38 59]]


In [57]:
# Bir matrisin elemanları ve indeksleriyle yapılan işlemler

# 1) En büyük elemanı bulma
print(f"en büyük eleman = {np.max(my_array_9)}")

# 2) En küçük elemanı bulma
print(f"en büyük eleman = {np.min(my_array_9)}")

# 3) En büyük elemanın indeks değerini getirme
print(f"en büyük elemanın indeksi = {np.argmax(my_array_9)}")

# 4) En küçük elemanın indeks değerini getirme
print(f"en küçük elemanın indeksi = {np.argmin(my_array_9)}")

en büyük eleman = 89
en büyük eleman = 1
en büyük elemanın indeksi = 2
en küçük elemanın indeksi = 4


In [59]:
# İstatistiki Bilgiler

# 1) Ortalama değer
print(f"Ortalama = {np.mean(my_array_9)}")

# 2) Standart Sapma
print(f"Standart Sapma = {np.std(my_array_9)}")

# 3) Median (ortanca değer)
print(f"Median = {np.median(my_array_9)}")

Ortalama = 56.416666666666664
Standart Sapma = 26.297840004245383
Median = 64.0


In [61]:
# np.where() fonksiyonunun içerisine yazacağımız koşul ile
# bir matris içerisinde istediğimiz filtrelemeyi yapıp, sadece bu 
# filtreleme işlemine indeksleri ya da değerleri getirebiliriz.

In [67]:
my_array_10 = np.array([55,-3,0,18,2,1,24,-36])
my_index_10 = np.where(my_array_10>5)

print(f"Matris = {my_array_10}")
print("-"*50)
print(f"İndeksler = {my_index_10}")

Matris = [ 55  -3   0  18   2   1  24 -36]
--------------------------------------------------
İndeksler = (array([0, 3, 6], dtype=int64),)


In [71]:
# Bu değerleri getiren kodu yazın
print(my_array_10[my_index_10])

[55 18 24]


In [79]:
my_array_11 = np.random.randint(1,16,(3,3))
print(my_array_11)
print("-"*50)
my_index_11 = np.where(my_array_11>5)
print(f"5'ten büyük sayıların İndeksleri = {my_index_11}")
print("-"*50)
print(f"Değerler = {my_array_11[my_index_11]}")

[[11  2  4]
 [ 6 13  1]
 [14  7  3]]
--------------------------------------------------
5'ten büyük sayıların İndeksleri = (array([0, 1, 1, 2, 2], dtype=int64), array([0, 0, 1, 0, 1], dtype=int64))
--------------------------------------------------
Değerler = [11  6 13 14  7]


In [86]:
# 3x3 boyutunda 1 ile 100 arasında rastgele değerlerden oluşan bir matris
# tanımlayın. Bu matristeki 10'dan büyük ve 2'nin katı olan değerlerin
# hem indekslerini yazdırın hem de o değerleri yazdırın

my_array_12 = np.random.randint(1,101,(3,3))

kosul_12 = (my_array_12>10) & (my_array_12%2==0)
my_index_12 = np.where(kosul_12)
print(f"Matris = {my_array_12}")
print(f"-"*50)
print(f"İndeksler = {my_index_12}")
print(f"-"*50)
print(f"Değerler = {my_array_12[my_index_12]}")

Matris = [[66 78 62]
 [20 55 93]
 [ 3  2  8]]
--------------------------------------------------
İndeksler = (array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))
--------------------------------------------------
Değerler = [66 78 62 20]


In [88]:
# Array'leri birleştirme

my_array_13 = np.array([1,2])
my_array_14 = np.array([3,4])

# Tek bir satır olarak birleştirme
print(f"Tek bir satır olarak birleştirme = {np.concatenate((my_array_13,my_array_14))}")
print(f"-"*50)
print(f"Alt alta birleştirme (n adet satır olarak birleştirme) = {np.stack((my_array_13,my_array_14))}")

Tek bir satır olarak birleştirme = [1 2 3 4]
--------------------------------------------------
Alt alta birleştirme (n adet satır olarak birleştirme) = [[1 2]
 [3 4]]


In [90]:
# Sadece benzersiz değerleri bir array'e ekleyen kod

my_array_15 = np.array([5,5,1,0,78,78,30,0,1,3,2,1])
print(f"Orijinal Array = {my_array_15}")

print("-"*50)

my_array_16_unique = np.unique(my_array_15)
print(f"Benzersiz değerler = {my_array_16_unique}")

Orijinal Array = [ 5  5  1  0 78 78 30  0  1  3  2  1]
--------------------------------------------------
Benzersiz değerler = [ 0  1  2  3  5 30 78]


In [92]:
# Array'deki verileri istenilen değer aralığına çekmek

my_array_17 = np.array([0,5,98,-3,27,36,45,102,18,23,29,30])
print(f"Orijinal Array = {my_array_17}")
print("-"*50)

my_array_18_clip = np.clip(my_array_17,2,50)
print(f"Manipüle edilmiş Array = {my_array_18_clip}")

Orijinal Array = [  0   5  98  -3  27  36  45 102  18  23  29  30]
--------------------------------------------------
Manipüle edilmiş Array = [ 2  5 50  2 27 36 45 50 18 23 29 30]


In [94]:
#np.linspace() verilen aralıkta istenen sayı kadar eşit bölme yapar
# 0 ve 1 aralığında 5 adet eşit aralıklarla ayrılmış değer getiren kod

my_array_19 = np.linspace(0,1,5)
print(my_array_19)

[0.   0.25 0.5  0.75 1.  ]


In [102]:
my_list_2 = [55,-3,0,-2,11,11,-3,49,-26,-20,13,79,-8,49,76,103,38,-28]

# Aşama-1: Önce size verilen tekrar eden değerlerden kurtulun
# Aşama-1 tüyo: bu listeyi set veri yapısına dönüştürün

# önce listeyi set veri yapısına dönüştürüp tekrar eden verilerden kurtuluyoruz
my_set_1 = set(my_list_2)
print(f"Listenin orijinal hali = {my_list_2}")
print(f"-"*50)
print(f"Set'e dönüştürülmüş hali = {my_set_1}")
print(f"-"*50)

# Aşama-2: Elinizde kalan ve tekrar etmeyen verileri sıralayın
my_list_3_sirali = sorted(list(my_set_1))
print(f"Sıralı liste = {my_list_3_sirali}")
print(f"-"*50)
print(type(my_list_3_sirali))

# Aşama-3: Bu verileri bir array tipine dönüştürün ve ekrana yazdırın
my_array_final = np.array(my_list_3_sirali)
print(f"Final Sorted Array = {my_array_final}")
print(type(my_array_final))

Listenin orijinal hali = [55, -3, 0, -2, 11, 11, -3, 49, -26, -20, 13, 79, -8, 49, 76, 103, 38, -28]
--------------------------------------------------
Set'e dönüştürülmüş hali = {0, -28, -26, 103, 38, 11, -20, 13, 76, 79, 49, 55, -8, -3, -2}
--------------------------------------------------
Sıralı liste = [-28, -26, -20, -8, -3, -2, 0, 11, 13, 38, 49, 55, 76, 79, 103]
--------------------------------------------------
<class 'list'>
Final Sorted Array = [-28 -26 -20  -8  -3  -2   0  11  13  38  49  55  76  79 103]
<class 'numpy.ndarray'>
